version: '3'

services:

  web:
    container_name: web
    image: ahmatda/ahmatda-app
    expose:
      - "8080"
    ports:
      - "8080:8080"

  nginx:
    container_name: nginx
    image: ahmatda/ahmatda-nginx
    restart: always
    ports:
      - "80:80"
      - "433:433"
    depends_on:
      - web
