version: '3'

services:

  web:
    container_name: web
    image: dkakwek/app-web
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: dkakwek/app-nginx
    ports:
      - 80:80
    depends_on:
      - web