spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: substituted-by-github-secrets
    username: substituted-by-github-secrets
    password: substituted-by-github-secrets
    hikari:
      maxLifetime: 500000
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 1000
    open-in-view: false

logging:
  config: classpath:logback-production.xml
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
