spring:
  datasource:
    url:
    driver-class-name:
    hikari:
      maxLifetime: 500000
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 1000
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace