name: Build and Deploy

on:
  push:
    branches: [ "main" ]
    
env:
  RESOURCE_PATH: ./application/src/main/resources/application-production.yml
  FIREBASE_ACCOUNT_PATH: ./application/src/main/resources/firebase/fcm-account.json
  TEST_RESOURCE_PATH: ./application/src/test/resources/application-production.yml
  AWS_REGION: ap-northeast-2
  EB_ENVIRONMENT_NAME: 3Team-ahmatda-ENV
  EB_APPLICATION_NAME: "[3Team]-ahmatda-API"
  EB_DEPLOYMENT_PACKAGE: ./docker-compose.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
      
    - name: Set yaml file
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ env.RESOURCE_PATH }}
      env:
        spring.datasource.url: ${{ secrets.DATASOURCE_URL }}
        spring.datasource.username: ${{ secrets.DATASOURCE_USERNAME }}
        spring.datasource.password: ${{ secrets.DATASOURCE_PASSWORD }}
        jpa.hibernate.ddl-auto: none

    - name: Set FCM account json
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ env.FIREBASE_ACCOUNT_PATH }}
      env:
        private_key_id: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
        private_key: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        
    - name: Grant for Gradle
      run : chmod +x gradlew
      
    - name: Build Gradle
      run: ./gradlew clean build
    
    - name: jacoco report
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        title: 테스트 커버리지 리포트
        paths: ${{ github.workspace }}/application/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 20
        min-coverage-changed-files: 20
    
    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        format: YYYYMMDD_HH-mm-ss
        utcOffset: "+09:00"
        
    - name: Show Current Time
      run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
      shell: bash
   
    ## docker build [Spring, Nginx]
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Login dockerhub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Spring boot Image Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ahmatda-app:latest
  
    - name: Nginx Image Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./nginx
        file: ./nginx/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ahmatda-nginx:latest
        
    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ env.AWS_REGION }}
        environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
        application_name: ${{ env.EB_APPLICATION_NAME }}
        deployment_package: ${{ env.EB_DEPLOYMENT_PACKAGE }}
        version_label: github-action-${{steps.current-time.outputs.formattedTime}}
        wait_for_environment_recovery: 90
