name: Build and Deploy

on:
  push:
    branches: [ "main" ]
    
env:
  RESOURCE_PATH: ./src/main/resources/application.yml
  TEST_RESOURCE_PATH: ./src/test/resources/application.yml
  AWS_REGION: ap-northeast-2
  EB_ENVIRONMENT_NAME: ahmatda-app-env
  EB_APPLICATION_NAME: ahmatda-app
  EB_DEPLOYMENT_PACKAGE: ./docker-compose.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
      
    - name: Run action
      uses: lpmi-13/learning-space-single-setup@v1.0.0
      env:
        spring.datasource.url: ${{ secrets.DATASOURCE_URL }}
        spring.datasource.username: ${{ secrets.DATASOURCE_USERNAME }}
        spring.datasource.password: ${{ secrets.DATASOURCE_PASSWORD }}
        jpa.hibernate.ddl-auto: none
      with:
        path: ${{ env.RESOURCE_PATH }}
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Grant for Gradle
      run : chmod +x gradlew
      
    - name: Build Gradle
      run: ./gradlew clean build
    
    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      with:
        format: YYYYMMDD_HH-mm-ss
        utcOffset: "+09:00"
        
    - name: Show Current Time
      run: echo "CurrentTime=${{ steps.current-time.outputs.formattedTime }}"
   
    ## docker build [Spring, Nginx]
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Login dockerhub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Spring boot Image Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ahmatda-app:latest
  
    - name: Nginx Image Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./nginx
        file: ./nginx/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ahmatda-nginx:latest
        
    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ env.AWS_REGION }}
        environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
        application_name: ${{ env.EB_APPLICATION_NAME }}
        deployment_package: ${{ env.EB_DEPLOYMENT_PACKAGE }}
        version_label: github-action-${{steps.current-time.outputs.formattedTime}}

      
      
